In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [2]:
arr=np.array(42)
print(arr)


42


In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
zeros_arr=np.zeros((5,2))
eros_arr=np.zeros(5)
print(zeros_arr)
zeros_arr=np.zeros((2,3))
print(zeros_arr)
print("Data type of the array:",zeros_arr.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
Data type of the array: float64


In [10]:
ones_arr=np.ones(6)
print(ones_arr)
empty_arr=np.empty((3,2))
print(empty_arr)

[1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
identity_matrix=np.eye(3)
print(identity_matrix)
identity_matrix=np.eye(4)
print("\n",identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [14]:
arr=np.array([1,2,3])
print("Before converting:",arr,arr.dtype)
new_arr=arr.astype('f')
print("After converting",new_arr,new_arr.dtype)

Before converting: [1 2 3] int64
After converting [1. 2. 3.] float32


In [16]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print("array 1\n",arr1,arr1.dtype)
print("array 1\n",arr2,arr2.dtype)
new_arr=arr1.astype(arr2.dtype)
print("New Array \n",new_arr,new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
array 1
 [-0.92404342 -1.58525442  2.1071646   1.07436552  1.51738877  1.31901389
 -1.28864665  0.37672548 -0.05361504  0.21005958] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [17]:
str_arr=np.array(['hello','world','numpy'])
print(str_arr)

['hello' 'world' 'numpy']


In [18]:
import numpy as np
a=np.array([1.,2.,3.,4.])
b=np.array([5.,6.,7.,8.])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [19]:
import numpy as np
arr=np.arange(12)
newarr=arr.reshape(4,3)
print(newarr)
newarr=arr.reshape((4,3),order='F')
print("\n",newarr)                   

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [24]:
arr=np.array([[1,2,3,4,9,10],[5,6,7,8,11,12]])
print(arr)
newarr=arr.reshape(3,2,2)
print("\n",newarr)
newarr1=newarr.reshape(3,-1)
print("\n reshape(3,-1) \n",newarr1)

[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape(3,-1) 
 [[ 1  2  3  4]
 [ 9 10  5  6]
 [ 7  8 11 12]]


In [23]:
original_arr=np.array([[10,20],[30,40]])
print("Original array:\n",original_arr)
flattened_arr=original_arr.flatten()
flattened_arr[0]=999
print("Flattened array:\n",flattened_arr)
print("Original array:\n",original_arr)
raveled_array=original_arr.ravel()
raveled_array[1]=888
print("Ravelled array:\n",raveled_array)
print("Original array:\n",original_arr)

Original array:
 [[10 20]
 [30 40]]
Flattened array:
 [999  20  30  40]
Original array:
 [[10 20]
 [30 40]]
Ravelled array:
 [ 10 888  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]


In [25]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[2,1],[3,5]])
greater_than=arr1>arr2
less=arr1<arr2
equal=arr1=arr2
print("Greater than:\n",greater_than)
print("\nLesser than:\n",less)
print("\nEqual to:\n",equal)

Greater than:
 [[False  True]
 [False False]]

Lesser than:
 [[ True False]
 [False  True]]

Equal to:
 [[2 1]
 [3 5]]


In [26]:
x=np.arange(10)
print("x=",x)
print("\n x[:5]=",x[:5])
print("\n x[4:7]=",x[4:7])
print("\n x[::2]=",x[::2])

x= [0 1 2 3 4 5 6 7 8 9]

 x[:5]= [0 1 2 3 4]

 x[4:7]= [4 5 6]

 x[::2]= [0 2 4 6 8]


In [28]:
x=np.arange(10)
print(x)
x[:5]=2
print("\n After broadcasting1",x)
x[::2]=100
print("\n After broadcasting2",x)

[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [2 2 2 2 2 5 6 7 8 9]

 After broadcasting2 [100   2 100   2 100   5 100   7 100   9]


In [29]:
x2=np.array([[12,5,2,4],
             [7,6,8,8],
             [1,6,7,7]])
print(x2[0])

[12  5  2  4]


In [31]:
x2=np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
print("\n x2[:2,:3]=\n",x2[:2,:3])


 x2[:2,:3]=
 [[12  5  2]
 [ 7  6  8]]


In [34]:
a=np.arange(12).reshape(3,4)
print("a=\n",a)
b=a>4
print("b=\n",b)
print("a[b]=\n",a[b])
a[b]=1
print("a=\n",a)

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]=
 [ 5  6  7  8  9 10 11]
a=
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [35]:
arr=np.arange(12).reshape((3,4))
\print(arr)
print("Transposing using .T")
print(arr.T)
print("Transpose using the transposal() function")
print(np.transpose(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transposing using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using the transposal() function
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [36]:
arr=np.arange(12).reshape((3,4))
print(np.dot(arr,arr.T))

[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [37]:
arr=np.arange(12).reshape((3,4))
print(arr)
print(np.swapaxes(arr,0,1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [38]:
result=np.dot(arr1,arr2)
print(result)

[[ 7  7]
 [21 28]]


In [40]:
result=np.matmul(arr1,arr2)
print(result)

[[ 7  7]
 [21 28]]
